refactor(main): update official site login

diff --git a/lib/account_login b/lib/account_login
--- a/lib/account_login
+++ b/lib/account_login
@@ -10,17 +10,18 @@ ___x_cmd_hub_login(){
         "")
                 ___x_cmd_ui_select "_SELECT" \
                     "Login Methods:" \
-                        "Open Browser to x-cmd.com" \
                         "Login With Weixin QR" \
-                        "Login With Email Verification"
+                        "Login With Email Verification" \
+                        "Open Browser to x-cmd.com"
                         # "Login With Telegram QR" \
                         # "Login With OneTime Password"    # SMS, Telegram, Email, Weixin
 
+                # TODO: Should move official site login to the first of the list
                 case "$_SELECT" in
-                    1)          ___x_cmd_hub_login_official_site "$@" ;;
                     # 2)          ___x_cmd_hub_login_telegram_qr "$@" ;;
-                    2)          ___x_cmd_hub_login_weixin_qr "$@" ;;
-                    3)          ___x_cmd_hub_login_email "$@" ;;
+                    1)          ___x_cmd_hub_login_weixin_qr "$@" ;;
+                    2)          ___x_cmd_hub_login_email "$@" ;;
+                    3)          ___x_cmd_hub_login_official_site "$@" ;;
                     *)          ;;
                 esac
                 ;;
@@ -29,7 +30,7 @@ ___x_cmd_hub_login(){
     esac
 }
 
-# Section: telegram weixin
+# Section: telegram, weixin, official_site
 
 ___x_cmd_hub_login_telegram_qr(){
     local TOKEN_TO_ACTIVATE
@@ -44,7 +45,7 @@ ___x_cmd_hub_login_weixin_qr(){
     token_to_activate="$(___x_cmd_hub_token_generate)"
 
     ___x_cmd_hub_print_qrcode "$(___x_cmd_hub_wechat_login_url "${token_to_activate}")"
-    printf "%s" "Please scan the QR code above, then press [Enter] to continue: "
+    printf "Please scan the QR code above, then press [Enter] to continue: "
     read -r _
 
     local userinfo
@@ -56,17 +57,25 @@ ___x_cmd_hub_login_weixin_qr(){
 }
 
 ___x_cmd_hub_login_official_site(){
-    if [ -n "$(___x_cmd_hub_token)" ]; then
-        # TODO: ask
-        printf "Detect token in this folder. Erase the token in the disk?" >&2
-        ___x_cmd_hub_token ""
+    # if [ -n "$(___x_cmd_hub_token)" ]; then
+    #     # TODO: ask
+    #     printf "Detect token in this folder. Erase the token in the disk?\n" >&2
+    #     ___x_cmd_hub_token ""
+    # fi
+
+    local token_to_activate
+    token_to_activate="$(___x_cmd_hub_token_generate)"
+
+    ___x_cmd_http_browse "$___X_CMD_HUB_SERVICE_URL/xlogin?token_to_activate=${token_to_activate}"
+    printf "Please login to hub.x-cmd.com, then press [Enter] to continue: "
+    read -r _
+
+    local userinfo
+    if userinfo="$(___x_cmd_hub_get_and_save_userinfo_by_token "${token_to_activate}")" ; then
+        hub_log info "Login Successfully, ${userinfo})"
+    else
+        hub_log error "Login Failed"
     fi
-
-    local TOKEN_TO_ACTIVATE
-    TOKEN_TO_ACTIVATE="$(___x_cmd_hub_token_generate)"
-    ___x_cmd_hub_token "$TOKEN_TO_ACTIVATE"
-
-    echo ___x_cmd_http_browse "$___X_CMD_HUB_SERVICE_URL/login?token_to_activate=${TOKEN_TO_ACTIVATE}"
 }
 
 # EndSection
diff --git a/lib/account_registration b/lib/account_registration
--- a/lib/account_registration
+++ b/lib/account_registration
@@ -10,25 +10,46 @@ ___x_cmd_hub_register(){
                 ___x_cmd_ui_select "_SELECT" \
                     "Register Methods:" \
                         "Weixin QR" \
-                        # "Open Browser to x-cmd.com" \
+                        "Email Verification" \
+                        "Open Browser to x-cmd.com" \
                         # "Telegram Bot"
 
+                # TODO: Should move official site login to the first of the list
                 case "$_SELECT" in
-                    # 1)          ___x_cmd_hub_register_official_site "$@" ;;
-                    1)          ___x_cmd_hub_register_weixin "$@" ;;
-                  # 3)          ___x_cmd_hub_register_telegram "$@" ;;
+                    1)          ___x_cmd_hub_register_weixin        "$@" ;;
+                    2)          ___x_cmd_hub_register_email         "$@" ;;
+                    3)          ___x_cmd_hub_register_official_site "$@" ;;
+                    4)          ___x_cmd_hub_register_telegram      "$@" ;;
                     *)          ;;
                 esac
                 ;;
         *)
-                ___x_cmd_hub_register_official_site ;;
+                ___x_cmd_hub_register_official_site "$@" ;;
     esac
 }
 
 # Section: Registration
 
 ___x_cmd_hub_register_official_site(){
-    ___x_cmd_http_browse "$___X_CMD_HUB_SERVICE_URL/register"
+    if [ -n "$(___x_cmd_hub_token)" ]; then
+        # TODO: ask
+        printf "Detect token in this folder. Erase the token in the disk?" >&2
+        ___x_cmd_hub_token ""
+    fi
+
+    local token_to_activate
+    token_to_activate="$(___x_cmd_hub_token_generate)"
+
+    ___x_cmd_http_browse "$___X_CMD_HUB_SERVICE_URL/register?token_to_activate=${token_to_activate}"
+    printf "Please register to hub.x-cmd.com, then press [Enter] to continue: "
+    read -r _
+
+    local userinfo
+    if userinfo="$(___x_cmd_hub_get_and_save_userinfo_by_token "${token_to_activate}")" ; then
+        hub_log info "Register Successfully, ${userinfo})"
+    else
+        hub_log error "Register Failed"
+    fi
 }
 
 ___x_cmd_hub_register_weixin(){
