refactor(main): format code

diff --git a/lib/account b/lib/account
--- a/lib/account
+++ b/lib/account
@@ -30,24 +30,6 @@ ___x_cmd_hub_token_generate(){
     printf "%s%s" "$(date +%s)" "$(___x_cmd_hub_token_random_md5 "$@")" | ___x_cmd_hub_token_md5 "$@"
 }
 
-___x_cmd_hub_get_and_save_userinfo_by_token(){
-    local token="${1:?Please provide token}"
-
-    local res
-    if ! res="$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/account/user?token=${token}" 2>/dev/null)" ; then
-        hub_log error "Failed to get userinfo by token: $res"
-        return 1
-    fi
-    hub_log debug "response: ${res}"
-
-    local userid
-    local username
-    userid="$(printf "%s" "$res" | x jq -r '.id')"
-    username="$(printf "%s" "$res" | x jq -r '.username')"
-    ___x_cmd_hub_token "${userid}/${token}"
-    printf "%s\n" "${username} ${userid}"
-}
-
 # EndSection
 
 # Section: qrcode
@@ -70,7 +52,7 @@ ___x_cmd_hub_wechat_login_url(){
 
 # EndSection
 
-# Section(env): ___x_cmd_hub_login_user, ___x_cmd_hub_token
+# Section(env): ___x_cmd_hub_login_user, ___x_cmd_hub_token, ___x_cmd_hub_get_and_save_userinfo_by_token
 
 ___x_cmd_hub_login_user(){
     cat "$___X_CMD_HUB_ENV/.me" 2>/dev/null
@@ -98,6 +80,24 @@ ___x_cmd_hub_token(){
     #     printf "%s" "$res" > "$___X_CMD_HUB_ENV/.me"
     #     printf "%s" "$1" > "$___X_CMD_HUB_ENV/.token"
     # fi
+}
+
+___x_cmd_hub_get_and_save_userinfo_by_token(){
+    local token="${1:?Please provide token}"
+
+    local res
+    if ! res="$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/account/user?token=${token}" 2>/dev/null)" ; then
+        hub_log error "Failed to get userinfo by token: $res"
+        return 1
+    fi
+    hub_log debug "response: ${res}"
+
+    local userid
+    local username
+    userid="$(printf "%s" "$res" | x jq -r '.id')"
+    username="$(printf "%s" "$res" | x jq -r '.username')"
+    ___x_cmd_hub_token "${userid}/${token}"
+    printf "%s\n" "${username} ${userid}"
 }
 
 # EndSection
