refactor(main): use ___x_cmd_httpget log

diff --git a/lib/file b/lib/file
--- a/lib/file
+++ b/lib/file
@@ -3,10 +3,10 @@
 ___x_cmd_hub_file(){
     local subcmd="$1";  [ "$#" -gt 0 ] && shift
     case "$subcmd" in
-        ls)             ___x_cmd_hub_file_ls "$@" ;;
-        which)           "$@" ;;
-        upload)         ___x_cmd_hub_file_upload "$@" ;;
-        share)          ___x_cmd_hub_file_share "$@" ;;
+        ls)             ___x_cmd_hub_file_ls      "$@" ;;
+        which)          ___x_cmd_hub_file_which   "$@" ;;
+        upload)         ___x_cmd_hub_file_upload  "$@" ;;
+        share)          ___x_cmd_hub_file_share   "$@" ;;
         private)        ___x_cmd_hub_file_private "$@" ;;
     esac
 }
@@ -15,16 +15,12 @@ ___x_cmd_hub_file_ls(){
     local respath="${1:-@me/}"
     respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
 
-    local url
     local res
-    url="$___X_CMD_HUB_SERVICE_URL/api/v0/file/ls?token=$(___x_cmd_hub_token)&res=${respath}"
-    res="$(curl "$url" 2>/dev/null)"
-    hub_log debug "res: $res, url: $url"
-
-    if [ "${res#ERR=}" != "$res" ]; then
-        hub_log error "$res"
+    if ! res="$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/file/ls?token=$(___x_cmd_hub_token)&res=${respath}")" ; then
+        hub_log error "Failed to ls file: $res"
         return 1
     fi
+    hub_log debug "response: ${res}"
 
     printf "%s" "$res" | x jq -r ".[]"
 }
@@ -45,7 +41,8 @@ ___x_cmd_hub_file_which(){
     respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
 
     local CACHE="${___X_CMD_ROOT%/}/${respath#/}"
-    if ___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/file/cat?token=$(___x_cmd_hub_token)&res=${respath}"; then
+    mkdir -p "${CACHE%/*}"
+    if ___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/file/cat?token=$(___x_cmd_hub_token)&res=${respath}" >"$CACHE"; then
         printf "%s" "$CACHE"
     else
         printf "Failed: %s" "$CACHE" 2>/dev/null
@@ -80,17 +77,15 @@ ___x_cmd_hub_file_upload(){
     local respath="${2:?provide respath}"
 
     [ ! -f "$localfp" ] && {
-        printf "File Not Existed: %s\n" "$localfp" >&2
+        hub_log error "File Not Existed: $localfp"
         return
     }
 
     respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
 
-    local url
-    url="$___X_CMD_HUB_SERVICE_URL/api/v0/file/upload?token=$(___x_cmd_hub_token)&res=${respath}"
-    curl -F "file=@$localfp" "$url" 2>/dev/null
+    # TODO: Wait ___x_cmd_httpget support -F "file=@$localfp"
+    curl -F "file=@$localfp" "$___X_CMD_HUB_SERVICE_URL/api/v0/file/upload?token=$(___x_cmd_hub_token)&res=${respath}" 2>/dev/null
     printf "\n"
-    hub_log debug "url: $url"
 }
 
 ___x_cmd_hub_file_share(){
