refactor: add client and testcase

diff --git a/lib/file b/lib/file
--- a/lib/file
+++ b/lib/file
@@ -20,7 +20,7 @@ ___x_cmd_hub_file_ls(){
     respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
 
     local res
-    if ! res="$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/file/ls?token=$(___x_cmd_hub_token)&res=${respath}")" ; then
+    if ! res="$(___x_cmd_hub_client_file_ls "$respath")" ; then
         hub:error "Failed to ls file: $res"
         return 1
     fi
@@ -43,18 +43,12 @@ A
     local respath="${1:?Provide respath}"
     respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
 
-    local cache_path="${___X_CMD_HUB_ENV}/.cache/${respath#/}"
-    local cache_expiration=1
-    mkdir -p "${cache_path%/*}"
-    local error_msg
-    if ___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/file/cat?token=$(___x_cmd_hub_token)&res=${respath}" "$cache_path" "$cache_expiration" error_msg; then
-        chmod +x "$cache_path"
-        hub:debug "Downloaded ${respath} to ${cache_path}"
-        printf "%s\n" "$cache_path"
-    else
-        hub:error "Failed: $error_msg. Please check the respath."
+    if ! res=$(___x_cmd_hub_client_file_cat "$respath"); then
+        hub:error "Failed: $res. Please check the respath."
         return 1
     fi
+
+    printf "%s\n" "$res"
 }
 
 # TODO: Should be review. @el
@@ -74,7 +68,15 @@ ___x_cmd_hub_file_normalize_respath(){
 }
 
 ___x_cmd_hub_file_upload(){
-    param:void
+    param:dsl<<A
+advise:
+    #1    ___advise_ls
+option:
+    #1    "local  path"
+    #2    "remote path"
+A
+    param:run
+
     local localfp="${1:?Provide local file}"
     local respath="${2:?provide respath}"
 
@@ -84,10 +86,7 @@ ___x_cmd_hub_file_upload(){
     }
 
     respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
-
-    # TODO: Wait ___x_cmd_httpget support -F "file=@$localfp"
-    curl -F "file=@$localfp" "$___X_CMD_HUB_SERVICE_URL/api/v0/file/upload?token=$(___x_cmd_hub_token)&res=${respath}" 2>/dev/null
-    printf "\n"
+    ___x_cmd_hub_client_file_upload "$localfp" "$respath"
 }
 
 ___x_cmd_hub_file_share(){
@@ -95,7 +94,7 @@ ___x_cmd_hub_file_share(){
     local respath="${1:?Please provide path}"
     respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
 
-    if ! res="$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/file/share/true?token=$(___x_cmd_hub_token)&res=${respath}")" ; then
+    if ! res="$(___x_cmd_hub_client_file_share "${respath}")" ; then
         hub:error "Failed to share file: $res"
         return 1
     fi
@@ -108,7 +107,7 @@ ___x_cmd_hub_file_private(){
     local respath="${1:?Please provide path}"
     respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
 
-    if ! res="$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/file/share/false?token=$(___x_cmd_hub_token)&res=${respath}")" ; then
+    if ! res="$(___x_cmd_hub_client_file_private "${respath}")" ; then
         hub:error "Failed to private file: $res"
         return 1
     fi
