refactor(log): hub_log -> hub:xxx

diff --git a/lib/file b/lib/file
--- a/lib/file
+++ b/lib/file
@@ -21,10 +21,10 @@ ___x_cmd_hub_file_ls(){
 
     local res
     if ! res="$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/file/ls?token=$(___x_cmd_hub_token)&res=${respath}")" ; then
-        hub_log error "Failed to ls file: $res"
+        hub:error "Failed to ls file: $res"
         return 1
     fi
-    hub_log debug "response: ${res}"
+    hub:debug "response: ${res}"
 
     local code
     code="$(xrc cat awk/lib/default.awk awk/lib/json.awk awk/lib/jiter.awk )"
@@ -42,10 +42,10 @@ ___x_cmd_hub_file_which(){
     mkdir -p "${cache_path%/*}"
     if ___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/file/cat?token=$(___x_cmd_hub_token)&res=${respath}" "$cache_path" "$cache_expiration"; then
         chmod +x "$cache_path"
-        hub_log debug "Downloaded ${respath} to ${cache_path}"
+        hub:debug "Downloaded ${respath} to ${cache_path}"
         printf "%s\n" "$cache_path"
     else
-        hub_log error "Failed: ___x_cmd_httpget return $?, you can use 'x log +x' to open the debug log"
+        hub:error "Failed: ___x_cmd_httpget return $?, you can use 'x log +x' to open the debug log"
         return 1
     fi
 }
@@ -72,7 +72,7 @@ ___x_cmd_hub_file_upload(){
     local respath="${2:?provide respath}"
 
     [ ! -f "$localfp" ] && {
-        hub_log error "File Not Existed: $localfp"
+        hub:error "File Not Existed: $localfp"
         return
     }
 
@@ -89,11 +89,11 @@ ___x_cmd_hub_file_share(){
     respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
 
     if ! res="$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/file/share/true?token=$(___x_cmd_hub_token)&res=${respath}")" ; then
-        hub_log error "Failed to share file: $res"
+        hub:error "Failed to share file: $res"
         return 1
     fi
 
-    hub_log info "File shared successfully: $res"
+    hub:info "File shared successfully: $res"
 }
 
 ___x_cmd_hub_file_private(){
@@ -102,9 +102,9 @@ ___x_cmd_hub_file_private(){
     respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
 
     if ! res="$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/file/share/false?token=$(___x_cmd_hub_token)&res=${respath}")" ; then
-        hub_log error "Failed to private file: $res"
+        hub:error "Failed to private file: $res"
         return 1
     fi
 
-    hub_log info "File private successfully: $res"
+    hub:info "File private successfully: $res"
 }
